// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Counts the primes below `n` by trial division, the same algorithm as
/// `DemoService.crunch`, so the two times compare.
int countPrimes({required int n}) =>
    RustLib.instance.api.crateApiDemoCountPrimes(n: n);

/// The target this copy of the crate was compiled for, e.g.
/// `wasm32-unknown (single-threaded)` or `x86_64-linux`.
String buildTarget() => RustLib.instance.api.crateApiDemoBuildTarget();
