// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An example binding. Replace with the crates the core needs.
PlatformInt64 add({required PlatformInt64 a, required PlatformInt64 b}) =>
    RustLib.instance.api.crateApiSimpleAdd(a: a, b: b);
