name: demo_cli
description: The demo command line. On WebUI it is also the root process (serve).
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

executables:
  demo: demo

dependencies:
  args: ^2.7.0
  squadron: ^7.4.4
  demo_core: any
  squadron_process:
    git:
      url: https://github.com/p0g-stack/squadron_process
      ref: d6c561bc60a72556fc6fa83bb90871fe8c978a4e

dev_dependencies:
  flutter_webui_client:
    git:
      url: https://github.com/p0g-stack/flutter-webui
      path: packages/flutter_webui_client
      ref: 9c5c6318f4ec4d878d90a0def5ee0f514fcd6591
  flutter_webui_root:
    git:
      url: https://github.com/p0g-stack/flutter-webui
      path: packages/flutter_webui_root
      ref: 9c5c6318f4ec4d878d90a0def5ee0f514fcd6591
  lints: ^6.1.0
  test: ^1.31.1
