name: demo_cli
description: The demo command line. On WebUI it is also the root process (serve).
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

executables:
  demo: demo

dependencies:
  args: ^2.7.0
  squadron: ^7.4.4
  demo_core: any
  squadron_process:
    git:
      url: https://github.com/p0g-stack/squadron_process
      ref: 52ee2f66b0928dbcb2a33a39a04d9f7e72f697f8

dev_dependencies:
  flutter_webui_client:
    git:
      url: https://github.com/p0g-stack/flutter-webui
      path: packages/flutter_webui_client
      ref: 3049dc94adb1df919ccdab1ab305759601a772c3
  flutter_webui_root:
    git:
      url: https://github.com/p0g-stack/flutter-webui
      path: packages/flutter_webui_root
      ref: 3049dc94adb1df919ccdab1ab305759601a772c3
  lints: ^6.1.0
  test: ^1.31.1
