# The workspace root file carries the p0g_lints plugin.
include:
  - package:flutter_lints/flutter.yaml
  - ../analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - build/**
    - web/**
    - linux/**
