name: demo
description: The demo GUI. Flutter on top of the core.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  squadron: ^7.4.4
  squadron_process:
    git:
      url: https://github.com/p0g-stack/squadron_process
      ref: d6c561bc60a72556fc6fa83bb90871fe8c978a4e
  flutter_webui_client:
    git:
      url: https://github.com/p0g-stack/flutter-webui
      path: packages/flutter_webui_client
      ref: 9ee7918d3ec1ab69e2cb415a079215e4224a12dd
  demo_core: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
